{{- if and .Values.apiKey.value (not .Values.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asr.fullname" . }}
  labels:
    {{- include "asr.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.apiKey.existingSecretKey }}: {{ .Values.apiKey.value | b64enc | quote }}
{{- end }}
