#!/usr/bin/env bash
# Regenerates deploy/kubernetes/*.yaml from the Helm chart so plain-kubectl
# users get the same, tested manifests. CI fails if they drift.
set -euo pipefail
cd "$(dirname "$0")/.."
chart=deploy/helm/temsai-asr-server
header="# Generated by scripts/render-manifests.sh from the Helm chart — do not edit.
# Apply with: kubectl apply -n <namespace> -f"
render() {
  local out=$1; shift
  { echo "$header deploy/kubernetes/$out"
    helm template temsai-asr-server "$chart" --set fullnameOverride=temsai-asr-server "$@" \
      | grep -vE '^\s*(helm.sh/chart|app.kubernetes.io/managed-by):'
  } > "deploy/kubernetes/$out"
}
render cpu.yaml
render gpu.yaml -f "$chart/values-gpu.yaml"
echo "rendered deploy/kubernetes/{cpu,gpu}.yaml"
